### PR TITLE
RHCLOUD-29101 Introduce recipients.emails field

### PR DESCRIPTION
**Pull request by gwenneg**
Same as https://github.com/RedHatInsights/insights-schemas-java/pull/113.

### CODE REVIEW

**Comment by josejulio** [comment]
That part of the code is auto-generated - we need to modify the [event-schema's notifications file](https://github.com/RedHatInsights/event-schemas/blob/main/schemas/core/v1/notification.json#L25) - upon merging that, this repo will pick that change and generate that.

**Comment by josejulio** [comment]
The updated tests will still be useful after merging that work

**Comment by gwenneg** [comment]
Yeah, that's what I just figured out :sweat_smile: Sorry for the noise!

**Review by josejulio — APPROVED** [review]
lgtm

**Pull request merged**
